name: MMOBuffs
version: '20250421-fork'
main: com.ehhthan.mmobuffs.MMOBuffs
api-version: 1.17
authors: [Ehhthan]
soft-depend: [PlaceholderAPI, MythicLib, AureliumSkills]

commands:
  mmobuffs:
    description: Main command for MMOBuffs
    usage: /<command>
    aliases: [mmobuff, buffs, buff]
